### PR TITLE
Small fixes

### LINKED ISSUE #10: Typo in variable name.
I think `kinetic_ernergy` is supposed to be `kinetic_energy`. See:
https://github.com/aesara-devs/aehmc/blob/87b0c4d20c276d191522132c1f3f00fec70239b1/aehmc/hmc.py#L22-L27

The latter spelling is used in other places like https://github.com/aesara-devs/aehmc/blob/87b0c4d20c276d191522132c1f3f00fec70239b1/aehmc/integrators.py#L46

### PR DESCRIPTION
**Pull request by rlouf**
These changes close #10 and #12.

### CODE REVIEW

**Review by zoj613 — DISMISSED** [review]
LGTM, thanks.

**Comment by zoj613** [comment]
Are the failures a result of the changes?

**Comment by rlouf** [comment]
Tests pass locally, must have something to do with the random seed used? Anyway, this should not happen so I'll investigate.

**Comment by rlouf** [comment]
@zoj613 ready to review, something must have changed in aesara's random number generator since the version on my machine.

**Review by zoj613 — APPROVED** [review]

**Comment by rlouf** [comment]
@brandonwillard this needs a review from someone with write access.

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
