### PR TITLE
Replace aet aliases with at.

### PR DESCRIPTION
**Pull request by twiecki**
See https://github.com/aesara-devs/aesara/issues/328 for the motivation.

### CODE REVIEW

**Comment by rlouf** [comment]
Yes! I've noticed the aesara documentation still uses `aet` in many places as well.

**Comment by twiecki** [comment]
I have a pr to change that too.

**Comment by twiecki** [comment]
Changed in aesara by https://github.com/aesara-devs/aesara/pull/728.

**Comment by rlouf** [comment]
Thank you!

**Pull request merged**
