### PR TITLE
Update isort version in pre-commit config file.

### LINKED ISSUE #94: pre-commit hooks setup is failing.
## Description of your problem or feature request
Setting up pre-commit hooks fails due to a bug in `isort` explained here: https://github.com/PyCQA/isort/issues/2083
**Please provide a minimal, self-contained, and reproducible example.**
```
pre-commit install-hooks
```

**Please provide the full traceback of any errors.**
```
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/zoj/.cache/pre-commit/repopytli6no/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/zoj/.cache/pre-commit/repopytli6no
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error

      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Traceback (most recent call last):
            File "/home/zoj/.cache/pre-commit/repopytli6no/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/zoj/.cache/pre-commit/repopytli6no/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/zoj/.cache/pre-commit/repopytli6no/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-218ucduw/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-218ucduw/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
Check the log at /home/zoj/.cache/pre-commit/pre-commit.log
```

**Please provide any additional information below.**
We need to update the isort version in the precommit config to 5.12.0

## Versions and main components

* Aesara version: 2.8.12
* Aesara config (`python -c "import aesara; print(aesara.config)"`)
* Python version: 3.11
* Operating system: Linux
* How did you install Aesara: conda

### PR DESCRIPTION
**Pull request by zoj613**
Setting up the pre-commit hooks fails due to a bug in isort (see: https://github.com/PyCQA/isort/issues/2083). This commit updates the version to 5.12.0 where this bug was fixed.

closes #94 

**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.  If your commit description starts with "Fix...", then you're probably making this mistake.
+ [x] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Review by brandonwillard — COMMENTED** [review]
We need to make it so that "Check code style" runs when the `pre-commit` config changes.  Right now, the requisite check is being skipped.

**Comment by zoj613** [comment]
> We need to make it so that "Check code style" runs when the `pre-commit` config changes. Right now, the requisite check is being skipped.

Is this a hook specified somewhere? I dont see it in the config.

**Comment by zoj613** [comment]
@brandonwillard could you check this again. The test failure is the unrelated `DisconnectedInputError` that was mentioned earlier.

**Review by brandonwillard — COMMENTED** [review]
I added a PR that brings this project setup up to speed with the other Aesara projects: https://github.com/aesara-devs/aehmc/pull/98.  Out of necessity, it also covers the `pre-commit` and a different `urllib3` fix, so we can close this one.

**Pull request closed without merging**
